let firstInteger = 23;
let secondInteger = 37;
let sum = firstInteger + secondInteger;
let difference = firstInteger - secondInteger;
let multiplication = firstInteger * secondInteger;
let division = firstInteger / secondInteger;
let reminderDivision = firstInteger % secondInteger;
console.log("Сума :" , sum);
console.log("Разлика :" , difference);
console.log("Произведение :" , multiplication);
console.log("Деление :" , division);
console.log("Целочислено деление :" , reminderDivision);